# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: companycompany
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: serverless-test-1
service: nuxt3-sample
provider:
  name: aws
  stage: dev
  region: ap-northeast-1
  runtime: nodejs16.x
package:
  patterns:
    - '!**'
    - '.output/**' # nuxt run buildの出力ディレクトリ
functions:
  NuxtSsrEngine:
    handler: '.output/server/index.handler'
    url: true # Lambda function URLを有効